name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
      # use gradle build applications
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      # gradlew executable
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      # run gradle wrapper and compile
      - name: Run gradle wrapper for compiling java
        run: ./gradlew clean compileJava compileTestJava

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: victortsai8001/spring-api-template:latest
