name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login to Dockerhub
      with: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    - name: build docker image
      run: docker build . --file Dockerfile --tag victorTsai8001/spring-api-template:$(date +%s)
    - name: docker push
      run: docker push ${{secrets.DOCKER_USER}}/spring-api-template
